# Demo Environment Configuration
# This file defines the demo environment settings for GitHub Actions

# Environment URL (optional)
url: https://roadmap-demo.nelaka.xyz/
# Required environment variables for deployment
# These must be set as repository secrets before deployment can proceed
secrets:
  - DROPLET_HOST
  - DROPLET_USER
  - DROPLET_SSH_KEY
  - DB_NAME # Production database
  - DB_USER # Shared database user
  - DB_PASS # Shared database password
  - DEMO_DB_NAME # Demo database (separate)
  - JWT_SECRET
# Note: Demo environment uses separate database name for data isolation
# but shares the same database user/password and server infrastructure
